---
apiVersion: v1
kind: Namespace
metadata:
  name: examples-gluster
---
apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
  namespace: examples-gluster
subsets:
  - addresses:
      - ip: 192.168.50.31
    ports:
      - port: 1
  - addresses:
      - ip: 192.168.50.32
    ports:
      - port: 1
  - addresses:
      - ip: 192.168.50.33
    ports:
      - port: 1

---
kind: Service
apiVersion: v1
metadata:
  name: glusterfs-cluster
spec:
  ports:
  - port: 1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  glusterfs:
    endpoints: glusterfs-cluster
    path: pv01
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: examples-gluster
spec:
  accessModes:
  - ReadWriteOnce
  resources:
     requests:
       storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: examples-gluster
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: examples-gluster
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql # has to match .spec.template.metadata.labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      restartPolicy: Always
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: changeme
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-volume
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rancher"
      volumes:
      - name: mysql-volume
        persistentVolumeClaim:
          claimName: mysql-pvc